BEGIN;

SELECT plan(23);

SELECT trigger_is('inventario',
                  'carreteras_lugo',
                  'update_longitud',
                  'inventario',
                  'update_longitud');

SELECT trigger_is('inventario',
                  'carreteras_lugo',
                  'mirror_carreteras_lugo',
                  'inventario',
                  'mirror_carreteras_lugo');

SELECT trigger_is('inventario',
                  'carretera_municipio',
                  'update_longitud_carretera_municipio',
                  'inventario',
                  'update_longitud_carretera_municipio');

SELECT trigger_is('inventario',
                  'carretera_municipio',
                  'update_pks_m_1000',
                  'inventario',
                  'update_pks_1000');

SELECT trigger_is('inventario',
                  'pks_1000',
                  'update_geom_pks_1000',
                  'inventario',
                  'update_geom_point_on_pk_change');

SELECT trigger_is('inventario',
                  'carretera_municipio',
                  'update_pks_carreteras',
                  'inventario',
                  'update_pks_carreteras');

SELECT trigger_is('inventario',
                  'carreteras_lugo',
                  'update_codigo_carretera',
                  'inventario',
                  'update_codigo_carretera');

SELECT trigger_is('inventario',
                  'rampas',
                  'update_longitud',
                  'inventario',
                  'update_longitud');

SELECT trigger_is('inventario',
                  'variantes',
                  'update_longitud',
                  'inventario',
                  'update_longitud');

INSERT INTO inventario.carreteras_lugo
       (numero, pk_inicial, pk_final, the_geom)
       VALUES('6666', 0, 100, ST_GeomFromText('MULTILINESTRING((-70.729212 42.373848,-70.67569 42.375098))', 25829));
SELECT is(GeometryType(the_geom), 'MULTILINESTRINGM', 'carreteras - geom calibrated on INSERT')
       FROM inventario.carreteras
       WHERE numero = '6666';
SELECT is(codigo, 'LU-P-6666', 'Code autogenerated from numero')
       FROM inventario.carreteras
       WHERE numero = '6666';

INSERT INTO inventario.carreteras_lugo
       (numero, pk_inicial, pk_final, the_geom)
       VALUES('9999', 2, 23.5, ST_GeomFromText('MULTILINESTRING((-70.729212 42.373848,-70.67569 42.375098))', 25829));
SELECT is(longitud, '21500', 'carreteras - longitud calculated on INSERT')
       FROM inventario.carreteras
       WHERE numero = '9999';

INSERT INTO inventario.carretera_municipio
       (codigo_carretera, codigo_municipio, orden_tramo, pk_inicial_tramo, pk_final_tramo)
       VALUES('9999', '27001', 'A', 3, 9.65);
SELECT is(longitud_tramo, '6650', 'carretera_municipio - longitud calculated on INSERT')
       FROM inventario.carretera_municipio
       WHERE codigo_carretera = '9999' AND codigo_municipio = '27001' AND orden_tramo = 'A';
--last PK has no geom, so we should 7 records but only 6 valid geoms
SELECT is(COUNT(*), '7', 'PKS on tramo')
       FROM inventario.pks_1000
       WHERE codigo_carretera = '9999' AND codigo_municipio = '27001';
SELECT is(COUNT(the_geom), '6', 'PKs 1000 - geom autocalculated on INSERT')
       FROM inventario.pks_1000
       WHERE codigo_carretera = '9999' AND codigo_municipio = '27001';
SELECT is(pk_inicial, '3', 'PK inicial autocalculated on INSERT')
       FROM inventario.carreteras_lugo
       WHERE numero = '9999';
SELECT is(pk_final, '9.65', 'PK final autocalculated on INSERT')
       FROM inventario.carreteras_lugo
       WHERE numero = '9999';

UPDATE inventario.carretera_municipio
       SET pk_inicial_tramo = 6
       WHERE codigo_carretera = '9999'
             AND codigo_municipio = '27001';
--last PK has no geom, so we should get 4 records but only 3 valid geoms
SELECT is(COUNT(*), '4', 'PKS on tramo')
       FROM inventario.pks_1000
       WHERE codigo_carretera = '9999' AND codigo_municipio = '27001';
SELECT is(COUNT(the_geom), '3', 'PKS 1000 - geom autocalculated on UPDATE')
       FROM inventario.pks_1000
       WHERE codigo_carretera = '9999' AND codigo_municipio = '27001';
SELECT is(pk_inicial, '6', 'PK inicial autocalculated on UPDATE')
       FROM inventario.carreteras_lugo
       WHERE numero = '9999';
SELECT is(pk_final, '9.65', 'PK final autocalculated on UPDATE')
       FROM inventario.carreteras_lugo
       WHERE numero = '9999';

INSERT INTO inventario.rampas
       (codigo_carretera, pk_inicial, pk_final, the_geom)
       VALUES('9999', 2, 23.5, ST_GeomFromText('MULTILINESTRING((-70.729212 42.373848,-70.67569 42.375098))', 25829));
SELECT is(longitud, '21500', 'rampas - longitud calculated on INSERT')
       FROM inventario.rampas
       WHERE codigo_carretera = '9999';

INSERT INTO inventario.variantes
       (codigo_carretera, pk_inicial, pk_final, the_geom)
       VALUES('9999', 2, 23.5, ST_GeomFromText('MULTILINESTRING((-70.729212 42.373848,-70.67569 42.375098))', 25829));
SELECT is(longitud, '21500', 'variantes - longitud calculated on INSERT')
       FROM inventario.variantes
       WHERE codigo_carretera = '9999';

ROLLBACK;
